website/webproj/webapp/urls.py
from django.urls import path
from webapp import views


app_name = 'webapp'

urlpatterns = [
    path('',views.homepage,name='homepage'),
    path('pic1/',views.pic1,name='pic1'),
    path('pic2/',views.pic2,name='pic2'),
    path('pic3/',views.pic3,name='pic3'),
]

website/webproj/webproj/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('webapp.urls')),
    
    path('admin/', admin.site.urls),
]

website/webproj/webapp/models.py
from django.db import models

# Create your models here.

website/webproj/webapp/views.py
from django.shortcuts import render

# Create your views here.

def homepage(request):
    return render(request,'webapp/homepage.html')

def pic1(request):
    return render(request,'webapp/pic1.html')

def pic2(request):
    return render(request,'webapp/pic2.html')

def pic3(request):
    return render(request,'webapp/pic3.html')

website/webproj/templates/webapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </head>
  <body>


        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">

          <a class="navbar-brand" href="">

            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 612 612" focusable="false" role="img">
              <title>Bootstrap</title>
              <path fill="#563d7c" d="M612 510c0 56.1-45.9 102-102 102H102C45.9 612 0 566.1 0 510V102C0 45.9 45.9 0 102 0h408c56.1 0 102 45.9 102 102v408z"/>
              <path fill="#fff" d="M166.3 133h173.5c32 0 57.7 7.3 77 22s29 36.8 29 66.5c0 18-4.4 33.4-13.2 46.2-8.8 12.8-21.4 22.8-37.8 29.8v1c22 4.7 38.7 15.1 50 31.2 11.3 16.2 17 36.4 17 60.8 0 14-2.5 27.1-7.5 39.2-5 12.2-12.8 22.7-23.5 31.5s-24.3 15.8-41 21-36.5 7.8-59.5 7.8h-164V133zm62.5 149.5h102c15 0 27.5-4.2 37.5-12.8s15-20.8 15-36.8c0-18-4.5-30.7-13.5-38s-22-11-39-11h-102v98.6zm0 156.5h110.5c19 0 33.8-4.9 44.2-14.8 10.5-9.8 15.8-23.8 15.8-41.8 0-17.7-5.2-31.2-15.8-40.8s-25.2-14.2-44.2-14.2H228.8V439z"/>
            </svg>
          enji
          </a>
<div class="container">


          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>


<div class="topnav-centered">


            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:pic1' %}">Pic1</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:pic2' %}">Pic2</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:pic3' %}">Pic3</a>
              </li>
              </ul>
</div>
<ul class='navbar-nav'>


              <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:homepage' %}">Home</a>
              </li>
            </ul>
</div>


        </nav>
<div class="container">


        {% block body_block %}

        {% endblock %}
</div>
  </body>
</html>

website/webproj/templates/webapp/homepage.html
{% extends 'webapp/base.html' %}
{% block body_block %}
{%load static%}




<div class="jumbotron">
<h1 class="text-center">Benji's Homepage</h1>
</div>

<div class="row card-deck">


<div class="card text-white bg-primary mb-3" style="width: 18rem;">
  <img src="static/images/mimi.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Mimi :)</h5>
    <p class="card-text">Here is a picture of Mimi</p>
    <a href="{% url 'webapp:pic1' %}" class="btn btn-warning">Pic1</a>
  </div>
</div>

<div class="card text-white bg-warning mb-3" style="width: 18rem;">
  <img src="static/images/mimi2.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Mimi ;)</h5>
    <p class="card-text">Here is another one</p>
    <a href="{% url 'webapp:pic2' %}" class="btn btn-danger">Pic2</a>
  </div>
</div>

<div class="card text-white bg-success mb-3" style="width: 18rem;">
  <img src="static/images/mimi3.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Mimi c:</h5>
    <p class="card-text">One more for goood measure</p>
    <a href="{% url 'webapp:pic3' %}" class="btn btn-primary">Pic3</a>
  </div>
</div>

</div>



<div class="card">
  <div class="card-header">
    Quote
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>One man's trash is another man's Christmans gift for Dad!</p>
      <footer class="blockquote-footer">Gene Belcher <cite title="Source Title">Bob's Burgers, Season 5:Father of the Bob</cite></footer>
    </blockquote>
  </div>
</div>



{% endblock %}

website/webproj/templates/webapp/pic1.html
{% extends 'webapp/base.html' %}
{% block body_block %}
{%load static%}

<h1>hi this is a pic1 of mimi</h1>
<img src="{% static "images/mimiyawn.jpg" %}" alt="">


{% endblock %}

website/webproj/templates/webapp/pic2.html
{% extends 'webapp/base.html' %}
{% block body_block %}
{%load static%}

<h1>hi this is a pic1 of mimi</h1>
<img src="{% static "images/mimitoy.jpg" %}" alt="">


{% endblock %}

website/webproj/templates/webapp/pic3.html
{% extends 'webapp/base.html' %}
{% block body_block %}
{%load static%}

<h1>hi this is a pic1 of mimi</h1>
<img src="{% static "images/mimipink.jpg" %}" alt="">


{% endblock %}